### ISSUE TITLE
AttributeError in Sublime Text 2 when diff finds no differences

### ISSUE THREAD

**Issue by jtasker** [colinta/SublimeFileDiffs#64]
When I diff two identical files in Sublime Text 2, I get this error in the console:

```python
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
  File ".\file_diffs.py", line 432, in run
  File ".\file_diffs.py", line 97, in run_diff
AttributeError: 'View' object has no attribute 'show_popup'
```

It seems to have been introduced by commit 54a721f2f63fc31bb61c9ed28aa53ee3137d14a4 since the function `show_popup` doesn't exist in Sublime Text 2, [only in Sublime Text 3](https://www.sublimetext.com/forum/viewtopic.php?f=2&t=17583).

**Comment by colinta** [comment]
Ah interesting. Do you think you could add support for st2? I don't use it, and now that st3 has been around for so long, I'm not very compelled to continue to support it. I think a simple feature check here would do the trick. 

I'm out of the country on vacation, too, so i won't be able to merge a PR for a few days.
